version: '3'
services:
  db:
    image: postgres:10.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sample_app
    ports:
      - "3000:3000"
    depends_on:
      - db
