# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout

      - run:
          name: docker-compose build
          command: docker-compose build

      - run:
          name: docker-compose up
          command: docker-compose up -d

      - run:
          name: sleep for waiting launch db
          command: sleep 1

      # Database setup
      - run: docker-compose exec web bundle exec rails db:create db:migrate
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: docker-compose exec web bundle exec rails test

      - run:
          name: docker-compose down
          command: docker-compose down
